spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 105MB
      location: ./files
  datasource:
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/ddangui?serverTimezone=UTC&characterEncoding=UTF-8
  redis:
    host: localhost
    port: 6379
file:
  upload-dir: /uploads
auth:
  jwt:
    secret: ${DDANGUI_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    exp:
      refresh: ${REFRESH_TOKEN_EXP}
      access: ${ACCESS_TOKEN_EXP}
