spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 105MB
      location: C:/Temp
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ddangui?serverTimezone=UTC&characterEncoding=UTF-8
  redis:
    host: localhost
    port: 6379
file:
  upload-dir: /uploads
auth:
  jwt:
    secret: ${DDANGUI_SECRET}
    header: ${DDANGUI_HEADER}
    prefix: ${DDANGUI_PREFIX}
    exp:
      refresh: ${DDANGUI_REFRESH_EXP}
      access: ${DDANGUI_ACCESS_EXP}