name: Test    # name of this workflow
on:           # required type. defining when we start jobs It works with following syntax
# on : [push,pull_request] it works on any pull request and push.
  push:
    # if we don't set the branch when we start the jobs, github action do their jobs in any push. so, we can set the ignore with following syntax
    # branches-ignore:
    #   - hotfix/board
    # if you want to do job every 15 minutes, we can use following syntax
    # on:
    #   schedule:
    #     - cron: '*/15 * * * *'
    # we can ignore file when workflow running.
    # paths-ignore:
    # - src/**      if you want to not ignore file, you can use ! keyword like !src/resources/application.yml
    branches:
      - master
      - develop
      - board     # if you want to do jobs on the branches starting with 'release/', you can use like this - release/**
  pull_request:
    branches:
      - master
      - develop
env:
  EXAMPLE: example  # it means the environment variables. it works on every workflows

defaults:   # commands belong to defaults are works on every workflows
  run:
    shell: bash   # we only can use bash
    working-directory: scripts  # the shell in scripts directory will be run on any workflows

 workflows are made of one or more jobs.
 jobs are basically process in parallel
jobs:
  test_job:     # the name of job. each job must have an own id. ids are made from sneak method.
    name: job test  # the name will be shown in github.
    runs-on: ubuntu-20.04 # what operating system you want to run this job. this syntax is required.
  test_job_1:
    name: test
    runs-on: [self-hosted, linux] # if you want to run jobs on self-hosted runner you can use like this.
  test_job_2:
    needs: [test_job, test_job_1] # this job will be started after test_job and test_job_1 end successfully.
    name: needs test
    runs-on: ubuntu-20.04
  test_job_3:
    if: always()  # if you use this syntax, the job will be run after test_job.
    # but, the test_job_3 will be run Regardless of whether test_job's success or not.
    needs: test_job
    name: if test
    runs-on: ubuntu-20.04